[channel]
generator = utipod
xmlbase = http://174.89.235.81:8080/UCrp_UI8XtuYfpiqluWLD7Lw
title = "CNBC Television"
link = https://www.youtube.com/channel/UCrp_UI8XtuYfpiqluWLD7Lw
description = ""

[channel "image"]
url = https://yt3.ggpht.com/ytc/AMLnZu-AV_bYvI2D5M289VDkLZTAb1gshEFwJXpopSbGoA=s0

