[item]
guid = -9sFmFemV_w
title = "Jim Cramer's new 'Mad Money' set revealed at New York Stock Exchange"
description = "CNBC's Jim Cramer discusses the new 'Mad Money' set at the New York Stock Exchange. Cramer's first show from the new set premieres at 6 p.m. eastern Monday."
author = CNBC Television
source = https://www.youtube.com/channel/UCrp_UI8XtuYfpiqluWLD7Lw
link = https://www.youtube.com/watch?v=-9sFmFemV_w
category = "News & Politics"
pubdate = Mon, 18 Jul 2022 00:00:00 -0000
enclosure = -9sFmFemV_w.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/-9sFmFemV_w/maxresdefault.jpg

