[item]
guid = -ymj7O93Xeg
title = "Ford unveils 700 horsepower F-150 Raptor R pickup"
description = "Ford has unveiled the new Ford F-150 Raptor R, a high-performance pickup with a supercharged 5.2-liter V-8 engine that produces 700 horsepower and 640 foot-pounds of torque with its gasoline engine. This comes as auto companies transition toward electric fleets ."
author = CNBC Television
source = https://www.youtube.com/channel/UCrp_UI8XtuYfpiqluWLD7Lw
link = https://www.youtube.com/watch?v=-ymj7O93Xeg
category = "News & Politics"
pubdate = Mon, 18 Jul 2022 00:00:00 -0000
enclosure = -ymj7O93Xeg.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/-ymj7O93Xeg/maxresdefault.jpg

