[item]
guid = 0OnwDRPl5AU
title = "We think food commodity prices will continue to decline, says P.F. Chang CEO"
description = "Damola Adamolekun, P.F. Chang's CEO, joins 'Squawk on the Street' to discuss recession risks he is seeing from the consumer, if commodity price declines are helping the restaurant and how demand will fare for the rest of the year."
author = CNBC Television
source = https://www.youtube.com/channel/UCrp_UI8XtuYfpiqluWLD7Lw
link = https://www.youtube.com/watch?v=0OnwDRPl5AU
category = "News & Politics"
pubdate = Mon, 18 Jul 2022 00:00:00 -0000
enclosure = 0OnwDRPl5AU.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/0OnwDRPl5AU/hqdefault.jpg

