[item]
guid = 1Ply6mJxZHw
title = "David Konrad: The financials trade has been largely oversold"
description = "David Konrad, Managing Director of Equity Research at KBW, joins Worldwide Exchange to discuss bank earnings ahead of Bank of America and Goldman Sachs reports this morning."
author = CNBC Television
source = https://www.youtube.com/channel/UCrp_UI8XtuYfpiqluWLD7Lw
link = https://www.youtube.com/watch?v=1Ply6mJxZHw
category = "News & Politics"
pubdate = Mon, 18 Jul 2022 00:00:00 -0000
enclosure = 1Ply6mJxZHw.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/1Ply6mJxZHw/hqdefault.jpg

