[item]
guid = 2I2pISSCmZU
title = "Citi opens positive catalyst watch on Delta"
description = "The "Halftime Report" traders debate the biggest analyst calls of the day."
author = CNBC Television
source = https://www.youtube.com/channel/UCrp_UI8XtuYfpiqluWLD7Lw
link = https://www.youtube.com/watch?v=2I2pISSCmZU
category = "News & Politics"
pubdate = Mon, 18 Jul 2022 00:00:00 -0000
enclosure = 2I2pISSCmZU.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/2I2pISSCmZU/maxresdefault.jpg

