[item]
guid = 40oD9q3jL-4
title = "International and business travel is now picking up, says Cerity's Lebenthal"
description = "Cerity Partners' Jim Lebenthal joins 'Closing Bell: Overtime' to discuss where Delta stock is headed."
author = CNBC Television
source = https://www.youtube.com/channel/UCrp_UI8XtuYfpiqluWLD7Lw
link = https://www.youtube.com/watch?v=40oD9q3jL-4
category = "News & Politics"
pubdate = Mon, 18 Jul 2022 00:00:00 -0000
enclosure = 40oD9q3jL-4.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/40oD9q3jL-4/hqdefault.jpg

