[item]
guid = 5nxUMZLllKo
title = "Disney+ could have succeeded just as well without Fox, says Cowen's Creutz"
description = "Kutgun Maral of RBC Capital Markets and Doug Creutz of Cowen join 'The Exchange' to discuss streaming stocks like Netflix, Paramount Global and Disney."
author = CNBC Television
source = https://www.youtube.com/channel/UCrp_UI8XtuYfpiqluWLD7Lw
link = https://www.youtube.com/watch?v=5nxUMZLllKo
category = "News & Politics"
pubdate = Mon, 18 Jul 2022 00:00:00 -0000
enclosure = 5nxUMZLllKo.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/5nxUMZLllKo/maxresdefault.webp

