[item]
guid = 6ac-ttXPmmw
title = "IBM beats on top and bottom lines, reaffirms revenue growth forecast"
description = "CNBC's Kristina Partsinevelos joins 'Closing Bell: Overtime' to report on IBM's quarterly earnings and revenue."
author = CNBC Television
source = https://www.youtube.com/channel/UCrp_UI8XtuYfpiqluWLD7Lw
link = https://www.youtube.com/watch?v=6ac-ttXPmmw
category = "News & Politics"
pubdate = Mon, 18 Jul 2022 00:00:00 -0000
enclosure = 6ac-ttXPmmw.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/6ac-ttXPmmw/hqdefault.jpg

