[item]
guid = 6NG_ctM7rCc
title = "Insider's Claire Atkinson and Puck's Matt Belloni break down the Disney C-Suite clash"
description = "Claire Atkinson, Insider chief media correspondent, and Matthew Belloni, Puck founding partner, join 'Squawk Box' to discuss Disney's C-Suite clash."
author = CNBC Television
source = https://www.youtube.com/channel/UCrp_UI8XtuYfpiqluWLD7Lw
link = https://www.youtube.com/watch?v=6NG_ctM7rCc
category = "News & Politics"
pubdate = Mon, 18 Jul 2022 00:00:00 -0000
enclosure = 6NG_ctM7rCc.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/6NG_ctM7rCc/hqdefault.jpg

