[item]
guid = 6NvlnFr4YUU
title = "Exclusive: Raytheon CEO Greg Hayes says supply chain issues will persist into 2023 or 2024"
description = "Greg Hayes, CEO of Raytheon Technologies, joins Worldwide Exchange to preview the Farnborough Air Show."
author = CNBC Television
source = https://www.youtube.com/channel/UCrp_UI8XtuYfpiqluWLD7Lw
link = https://www.youtube.com/watch?v=6NvlnFr4YUU
category = "News & Politics"
pubdate = Mon, 18 Jul 2022 00:00:00 -0000
enclosure = 6NvlnFr4YUU.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/6NvlnFr4YUU/hqdefault.jpg

