[item]
guid = 7yRLqzv5e2A
title = "ETF Edge: Single-stock ETFs hit the market"
description = "Greg Bassuk, AXS Investments CEO, joins the 'Halftime Report' to discuss the pitfalls and pros of single-stock ETFs. The SEC has expressed concern over the risky nature of these investments."
author = CNBC Television
source = https://www.youtube.com/channel/UCrp_UI8XtuYfpiqluWLD7Lw
link = https://www.youtube.com/watch?v=7yRLqzv5e2A
category = "News & Politics"
pubdate = Mon, 18 Jul 2022 00:00:00 -0000
enclosure = 7yRLqzv5e2A.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/7yRLqzv5e2A/hqdefault.jpg

