[item]
guid = Abs5rbjwlLA
title = "Final Trades: Delta, Devon Energy & more"
description = "The "Halftime Report" traders give their top picks to watch for the second half."
author = CNBC Television
source = https://www.youtube.com/channel/UCrp_UI8XtuYfpiqluWLD7Lw
link = https://www.youtube.com/watch?v=Abs5rbjwlLA
category = "News & Politics"
pubdate = Mon, 18 Jul 2022 00:00:00 -0000
enclosure = Abs5rbjwlLA.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/Abs5rbjwlLA/hqdefault.jpg

