[item]
guid = B9ueVlAVPEU
title = "You'll see more M&A deal activity because investors were able to buy low, says GGV's Richards"
description = "Jeff Richards, GGV Capital managing partner, joins 'TechCheck' to discuss what inning we're in for the valuation reset in VC-backed tech companies, an uptick in deal activity and where the deals will happen going forward."
author = CNBC Television
source = https://www.youtube.com/channel/UCrp_UI8XtuYfpiqluWLD7Lw
link = https://www.youtube.com/watch?v=B9ueVlAVPEU
category = "News & Politics"
pubdate = Mon, 18 Jul 2022 00:00:00 -0000
enclosure = B9ueVlAVPEU.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/B9ueVlAVPEU/maxresdefault.jpg

