[item]
guid = bXWc8y6iP34
title = "Bank of America's loans grew $100 billion year-over-year, says CEO"
description = "Brian Moynihan, Bank of America CEO, joins 'Closing Bell' to discuss what Wall Street liked in Bank of America's Q2 earnings results, Moynihan's expectations for upcoming Federal Reserve moves and more."
author = CNBC Television
source = https://www.youtube.com/channel/UCrp_UI8XtuYfpiqluWLD7Lw
link = https://www.youtube.com/watch?v=bXWc8y6iP34
category = "News & Politics"
pubdate = Mon, 18 Jul 2022 00:00:00 -0000
enclosure = bXWc8y6iP34.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/bXWc8y6iP34/hqdefault.jpg

