[item]
guid = Cr4KjbAYtKw
title = "Europe remains a key concern for global markets, says Barclays' Desphande"
description = "Joyce Chang, JPMorgan chair of global research, and Maneesh Deshpande, Barclays head of U.S. equity strategy, join 'Squawk on the Street' to discuss what the drawdown on commodity prices mean for markets, the peak concern for global markets and more."
author = CNBC Television
source = https://www.youtube.com/channel/UCrp_UI8XtuYfpiqluWLD7Lw
link = https://www.youtube.com/watch?v=Cr4KjbAYtKw
category = "News & Politics"
pubdate = Mon, 18 Jul 2022 00:00:00 -0000
enclosure = Cr4KjbAYtKw.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/Cr4KjbAYtKw/maxresdefault.jpg

