[item]
guid = EaaYFRvcvvY
title = "Two-Minute Drill: CVS, DOX & WSM"
description = "Christian Ledoux, CAPTRUST director of investments, joins 'Closing Bell: Overtime' to offer his stock picks, including CVS, Amdocs Ltd. and Williams-Sonoma."
author = CNBC Television
source = https://www.youtube.com/channel/UCrp_UI8XtuYfpiqluWLD7Lw
link = https://www.youtube.com/watch?v=EaaYFRvcvvY
category = "News & Politics"
pubdate = Mon, 18 Jul 2022 00:00:00 -0000
enclosure = EaaYFRvcvvY.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/EaaYFRvcvvY/hqdefault.jpg

