[item]
guid = eEZnzeo8OUg
title = "If bank earnings maintain, then the markets can maintain a rally, says Aureus' Kari Firestone"
description = "Kari Firestone, Aureus Asset Management chairman and CEO, joins 'Squawk Box' to discuss big bank earnings and what it means for the markets."
author = CNBC Television
source = https://www.youtube.com/channel/UCrp_UI8XtuYfpiqluWLD7Lw
link = https://www.youtube.com/watch?v=eEZnzeo8OUg
category = "News & Politics"
pubdate = Mon, 18 Jul 2022 00:00:00 -0000
enclosure = eEZnzeo8OUg.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/eEZnzeo8OUg/hqdefault.jpg

