[item]
guid = F1afsy4dDdo
title = "Ben Emons: The strong dollar could put a strain on emerging markets"
description = "Ben Emons, Managing Director of Global Macro Strategy at Medley Global Advisors, joins Worldwide Exchange to discuss expectations for Fed rate hikes, the inflation picture, and emerging markets."
author = CNBC Television
source = https://www.youtube.com/channel/UCrp_UI8XtuYfpiqluWLD7Lw
link = https://www.youtube.com/watch?v=F1afsy4dDdo
category = "News & Politics"
pubdate = Mon, 18 Jul 2022 00:00:00 -0000
enclosure = F1afsy4dDdo.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/F1afsy4dDdo/hqdefault.jpg

