[item]
guid = FK9tKxx84AE
title = "Elon Musk-Twitter saga: A look at possible outcomes"
description = "Sara Fischer, Axios media reporter, joins 'Squawk Box' joins to discuss Elon Musk's ongoing lawsuit with Twitter."
author = CNBC Television
source = https://www.youtube.com/channel/UCrp_UI8XtuYfpiqluWLD7Lw
link = https://www.youtube.com/watch?v=FK9tKxx84AE
category = "News & Politics"
pubdate = Mon, 18 Jul 2022 00:00:00 -0000
enclosure = FK9tKxx84AE.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/FK9tKxx84AE/hqdefault.jpg

