[item]
guid = fN54E2BOWVE
title = "Airplane shortages will last a couple of years, says Air Lease CEO John Plueger"
description = "CNBC's Phil LeBeau joins 'Squawk Box' with John Plueger, Air Lease CEO, to discuss airline industry shortages, supply chain disruptions, and costs."
author = CNBC Television
source = https://www.youtube.com/channel/UCrp_UI8XtuYfpiqluWLD7Lw
link = https://www.youtube.com/watch?v=fN54E2BOWVE
category = "News & Politics"
pubdate = Mon, 18 Jul 2022 00:00:00 -0000
enclosure = fN54E2BOWVE.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/fN54E2BOWVE/hqdefault.jpg

