[item]
guid = FPKoC1TN6l4
title = "Goldman Sachs earnings beat second quarter estimates, strong bond trading"
description = "CNBC's Leslie Picker joins 'Squawk Box' to report Goldman Sachs earnings beat."
author = CNBC Television
source = https://www.youtube.com/channel/UCrp_UI8XtuYfpiqluWLD7Lw
link = https://www.youtube.com/watch?v=FPKoC1TN6l4
category = "News & Politics"
pubdate = Mon, 18 Jul 2022 00:00:00 -0000
enclosure = FPKoC1TN6l4.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/FPKoC1TN6l4/hqdefault.jpg

