[item]
guid = fplgVLORtO0
title = "Electric Hydrogen produces clean hydrogen via renewable energy"
description = "CNBC's Diana Olick reports on one company's method to reduce fossil fuels as they produce hydrogen to power autos."
author = CNBC Television
source = https://www.youtube.com/channel/UCrp_UI8XtuYfpiqluWLD7Lw
link = https://www.youtube.com/watch?v=fplgVLORtO0
category = "News & Politics"
pubdate = Mon, 18 Jul 2022 00:00:00 -0000
enclosure = fplgVLORtO0.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/fplgVLORtO0/maxresdefault.jpg

