[item]
guid = G5a0fhCT5DI
title = "Three Stock Lunch: Domino’s, Tesla and JB Hunt"
description = "Craig Johnson, Piper Sandler chief market technician, joins 'Power Lunch' to discus his technical take on three stocks: Domino’s, Tesla and JB Hunt."
author = CNBC Television
source = https://www.youtube.com/channel/UCrp_UI8XtuYfpiqluWLD7Lw
link = https://www.youtube.com/watch?v=G5a0fhCT5DI
category = "News & Politics"
pubdate = Mon, 18 Jul 2022 00:00:00 -0000
enclosure = G5a0fhCT5DI.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/G5a0fhCT5DI/maxresdefault.jpg

