[item]
guid = GENotssTZK4
title = "We'll see increased flow in the order book over next 12-18 months, says Boom Supersonic CEO"
description = "Blake Scholl, Boom Supersonic CEO, joins 'Squawk on the Street' to discuss the company's schedule to its first flight, the next catalyst for more firm orders for Boom Supersonic and if airlines prefer cheaper fuel costs or a faster flight."
author = CNBC Television
source = https://www.youtube.com/channel/UCrp_UI8XtuYfpiqluWLD7Lw
link = https://www.youtube.com/watch?v=GENotssTZK4
category = "News & Politics"
pubdate = Mon, 18 Jul 2022 00:00:00 -0000
enclosure = GENotssTZK4.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/GENotssTZK4/maxresdefault.jpg

