[item]
guid = GgxZg7oHGBE
title = "Price cuts in housing are inevitable, says Ivy Zelman"
description = "Ivy Zelman, Zelman & Associates CEO, joins 'Closing Bell' to discuss the major drop in homebuilder sentiment and what that means for the housing market."
author = CNBC Television
source = https://www.youtube.com/channel/UCrp_UI8XtuYfpiqluWLD7Lw
link = https://www.youtube.com/watch?v=GgxZg7oHGBE
category = "News & Politics"
pubdate = Mon, 18 Jul 2022 00:00:00 -0000
enclosure = GgxZg7oHGBE.mp4

[item "itunes"]
image = https://i.ytimg.com/vi/GgxZg7oHGBE/maxresdefault.jpg

