[item]
guid = gLm1JWlV1hc
title = "Cramer on Elon Musk's Twitter defense: Are you kidding? Is that the best you have?"
description = "‘Mad Money’ host Jim Cramer and the ‘Squawk on the Street’ team break down the Twitter-Musk lawsuit's latest developments."
author = CNBC Television
source = https://www.youtube.com/channel/UCrp_UI8XtuYfpiqluWLD7Lw
link = https://www.youtube.com/watch?v=gLm1JWlV1hc
category = "News & Politics"
pubdate = Mon, 18 Jul 2022 00:00:00 -0000
enclosure = gLm1JWlV1hc.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/gLm1JWlV1hc/hqdefault.jpg

