[item]
guid = Gs7Q8JYZTHY
title = "Boeing could be a very attractive investment over the next year, says CFRA's Scarola"
description = "Colin Scarola, CFRA Research senior equity analyst, joins 'Power Lunch' to discuss the latest news for Boeing, how long the company's road back will be and why buyers should look past Boeing's recent struggles."
author = CNBC Television
source = https://www.youtube.com/channel/UCrp_UI8XtuYfpiqluWLD7Lw
link = https://www.youtube.com/watch?v=Gs7Q8JYZTHY
category = "News & Politics"
pubdate = Mon, 18 Jul 2022 00:00:00 -0000
enclosure = Gs7Q8JYZTHY.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/Gs7Q8JYZTHY/maxresdefault.jpg

