[item]
guid = h-kXl40EsLs
title = "We need Saudi oil going to Europe, says RBC Capital's Helima Croft"
description = "Helima Croft, head of global commodity strategy at RBC Capital Markets, joins 'Squawk Box' to discuss oil and energy and Biden's trip to Saudi Arabia."
author = CNBC Television
source = https://www.youtube.com/channel/UCrp_UI8XtuYfpiqluWLD7Lw
link = https://www.youtube.com/watch?v=h-kXl40EsLs
category = "News & Politics"
pubdate = Mon, 18 Jul 2022 00:00:00 -0000
enclosure = h-kXl40EsLs.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/h-kXl40EsLs/hqdefault.jpg

