[item]
guid = Haobd59ax9o
title = "The market is pricing in a shallow recession, traders agree"
description = "The traders discuss whether the market is already pricing in a recession. With CNBC's Scott Wapner and the 'Halftime Report' investment committee, Bryn Talkington, Sarat Sethi, Stephen Weiss and Joe Terranova."
author = CNBC Television
source = https://www.youtube.com/channel/UCrp_UI8XtuYfpiqluWLD7Lw
link = https://www.youtube.com/watch?v=Haobd59ax9o
category = "News & Politics"
pubdate = Mon, 18 Jul 2022 00:00:00 -0000
enclosure = Haobd59ax9o.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/Haobd59ax9o/hqdefault.jpg

