[item]
guid = HByZTf4YzV8
title = "Airlines need to make sure their networks meet customer demands, says FAA's Bill Nolen"
description = "Bill Nolen, FAA acting administrator, joins 'Squawk Box' to discuss airline cancellations, summer travel demand, and the airline industry."
author = CNBC Television
source = https://www.youtube.com/channel/UCrp_UI8XtuYfpiqluWLD7Lw
link = https://www.youtube.com/watch?v=HByZTf4YzV8
category = "News & Politics"
pubdate = Mon, 18 Jul 2022 00:00:00 -0000
enclosure = HByZTf4YzV8.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/HByZTf4YzV8/hqdefault.jpg

