[item]
guid = hhlQXwfAMlY
title = "We're still very much invested in this market, says NewEdge's Dawson"
description = "Cameron Dawson, NewEdge Wealth CIO, joins 'The Exchange' to discuss whether the market could actually be setting up to take another leg lower."
author = CNBC Television
source = https://www.youtube.com/channel/UCrp_UI8XtuYfpiqluWLD7Lw
link = https://www.youtube.com/watch?v=hhlQXwfAMlY
category = "News & Politics"
pubdate = Mon, 18 Jul 2022 00:00:00 -0000
enclosure = hhlQXwfAMlY.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/hhlQXwfAMlY/maxresdefault.jpg

