[item]
guid = J28sI16jWZo
title = "Boeing is a mightier aircraft maker than Airbus, says Qatar CEO Akbar Al Baker"
description = "CNBC's Phil LeBeau joins 'Squawk Box' with Akbar Al Baker, Qatar CEO, to discuss the company, the airline industry, and his ongoing lawsuit with Airbus."
author = CNBC Television
source = https://www.youtube.com/channel/UCrp_UI8XtuYfpiqluWLD7Lw
link = https://www.youtube.com/watch?v=J28sI16jWZo
category = "News & Politics"
pubdate = Mon, 18 Jul 2022 00:00:00 -0000
enclosure = J28sI16jWZo.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/J28sI16jWZo/hqdefault.jpg

