[item]
guid = j3GnhvETbUo
title = "Excessive heat impact on Texas power and Bitcoin"
description = "Kristina Partsinevelos joins 'Squawk Box' to report on extreme heat in the south with possible blackouts."
author = CNBC Television
source = https://www.youtube.com/channel/UCrp_UI8XtuYfpiqluWLD7Lw
link = https://www.youtube.com/watch?v=j3GnhvETbUo
category = "News & Politics"
pubdate = Mon, 18 Jul 2022 00:00:00 -0000
enclosure = j3GnhvETbUo.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/j3GnhvETbUo/maxresdefault.jpg

