[item]
guid = Je8f5bBGLPU
title = "We're going to see moderation in inflation and supply-chain disruptions, says Ed Yardeni"
description = "Ed Yardeni of Yardeni Research joins 'Closing Bell: Overtime' to discuss his thoughts about the markets and why he feels inflation moderating and supply-chain issues easing."
author = CNBC Television
source = https://www.youtube.com/channel/UCrp_UI8XtuYfpiqluWLD7Lw
link = https://www.youtube.com/watch?v=Je8f5bBGLPU
category = "News & Politics"
pubdate = Mon, 18 Jul 2022 00:00:00 -0000
enclosure = Je8f5bBGLPU.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/Je8f5bBGLPU/maxresdefault.jpg

