[item]
guid = JM1L3Lobdsk
title = "Riot Blockchain shuts down operations to support power grid in Texas"
description = "Jason Les, Riot Blockchain CEO, joins 'Power Lunch' to discuss the cost-benefit analysis for crypto mining in today's environment, conserving energy and selling it back to the grid and more."
author = CNBC Television
source = https://www.youtube.com/channel/UCrp_UI8XtuYfpiqluWLD7Lw
link = https://www.youtube.com/watch?v=JM1L3Lobdsk
category = "News & Politics"
pubdate = Mon, 18 Jul 2022 00:00:00 -0000
enclosure = JM1L3Lobdsk.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/JM1L3Lobdsk/hqdefault.jpg

