[item]
guid = kLT00wyegTI
title = "I see no broad wave toward buying things, says Cramer"
description = "'Mad Money' host Jim Cramer joins 'Closing Bell: Overtime' to discuss today's market reversal and the proper way to invest in this market."
author = CNBC Television
source = https://www.youtube.com/channel/UCrp_UI8XtuYfpiqluWLD7Lw
link = https://www.youtube.com/watch?v=kLT00wyegTI
category = "News & Politics"
pubdate = Mon, 18 Jul 2022 00:00:00 -0000
enclosure = kLT00wyegTI.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/kLT00wyegTI/maxresdefault.jpg

