[item]
guid = LnTtZjkk5Z8
title = "There shouldn't be an all-out ban on stock trading in Congress, says former SEC Chair Jay Clayton"
description = "Jay Clayton, former U.S. Securities and Exchange Commission chair, joins 'Squawk Box' to discuss stock trading in congress, ESG, and the energy crisis."
author = CNBC Television
source = https://www.youtube.com/channel/UCrp_UI8XtuYfpiqluWLD7Lw
link = https://www.youtube.com/watch?v=LnTtZjkk5Z8
category = "News & Politics"
pubdate = Mon, 18 Jul 2022 00:00:00 -0000
enclosure = LnTtZjkk5Z8.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/LnTtZjkk5Z8/hqdefault.jpg

