[item]
guid = lQHC0ZmVLLQ
title = "Fed will have to do more to get demand down, says Roger Ferguson"
description = "Roger Ferguson, a distinguished fellow at the Council on Foreign Relations, joins 'Squawk Box' to discuss big bank earnings, the Fed, and inflation."
author = CNBC Television
source = https://www.youtube.com/channel/UCrp_UI8XtuYfpiqluWLD7Lw
link = https://www.youtube.com/watch?v=lQHC0ZmVLLQ
category = "News & Politics"
pubdate = Mon, 18 Jul 2022 00:00:00 -0000
enclosure = lQHC0ZmVLLQ.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/lQHC0ZmVLLQ/hqdefault.jpg

