[item]
guid = LtYdw7WAFrE
title = "Katz: The hope is the market takes earnings season in stride, and looks to the next 6-12 months"
description = "David Katz of Matrix Asset Advisors believes stocks will be significantly higher a year from now, and highlights names in the financial, consumer discretionary and medical products sectors."
author = CNBC Television
source = https://www.youtube.com/channel/UCrp_UI8XtuYfpiqluWLD7Lw
link = https://www.youtube.com/watch?v=LtYdw7WAFrE
category = "News & Politics"
pubdate = Mon, 18 Jul 2022 00:00:00 -0000
enclosure = LtYdw7WAFrE.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/LtYdw7WAFrE/hqdefault.jpg

