[item]
guid = MIyHoKAaeYY
title = "I think this is a solid earnings report for IBM, says Hightower's Link"
description = "Hightower's Stephanie Link and Alicia Levine of BNY Mellon joins 'Closing Bell: Overtime' to discuss IBM's earnings and where they see the markets headed from here."
author = CNBC Television
source = https://www.youtube.com/channel/UCrp_UI8XtuYfpiqluWLD7Lw
link = https://www.youtube.com/watch?v=MIyHoKAaeYY
category = "News & Politics"
pubdate = Mon, 18 Jul 2022 00:00:00 -0000
enclosure = MIyHoKAaeYY.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/MIyHoKAaeYY/maxresdefault.jpg

