[item]
guid = N8lXH0mzhqU
title = "LIVE: White House press secretary Karine Jean-Pierre holds a briefing with reporters — 7/18/22"
description = "White House press secretary Karine Jean-Pierre holds a press briefing with reporters on Monday. Jared Bernstein, member of the Council of Economic Advisers, joins Jean-Pierre for today’s press briefing.\n\n» Subscribe to CNBC TV: https://cnb.cx/SubscribeCNBCtelevision\n» Subscribe to CNBC: https://cnb.cx/SubscribeCNBC\n\nTurn to CNBC TV for the latest stock market news and analysis. From market futures to live price updates CNBC is the leader in business news worldwide.\n\nConnect with CNBC News Online\nGet the latest news: http://www.cnbc.com/\nFollow CNBC on LinkedIn: https://cnb.cx/LinkedInCNBC\nFollow CNBC News on Facebook: https://cnb.cx/LikeCNBC\nFollow CNBC News on Twitter: https://cnb.cx/FollowCNBC\nFollow CNBC News on Instagram: https://cnb.cx/InstagramCNBC\n\n#CNBC\n#CNBCTV\nLIVE: White House press secretary Karine Jean-Pierre holds a briefing with reporters — 7/18/22"
author = CNBC Television
source = https://www.youtube.com/channel/UCrp_UI8XtuYfpiqluWLD7Lw
link = https://www.youtube.com/watch?v=N8lXH0mzhqU
category = "News & Politics"
pubdate = Mon, 18 Jul 2022 00:00:00 -0000
enclosure = N8lXH0mzhqU.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/N8lXH0mzhqU/maxresdefault.jpg

