[item]
guid = Nk3VepYOmmc
title = "We're set up here to move a little bit higher, says Virtus Investment Partners' Joe Terranova"
description = "Where the market is headed from here, with CNBC's Scott Wapner and the 'Halftime Report' investment committee, Bryn Talkington, Sarat Sethi, Stephen Weiss and Joe Terranova."
author = CNBC Television
source = https://www.youtube.com/channel/UCrp_UI8XtuYfpiqluWLD7Lw
link = https://www.youtube.com/watch?v=Nk3VepYOmmc
category = "News & Politics"
pubdate = Mon, 18 Jul 2022 00:00:00 -0000
enclosure = Nk3VepYOmmc.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/Nk3VepYOmmc/maxresdefault.jpg

