[item]
guid = NoJqrl6pZ8k
title = "I would stay invested, there's opportunity here, says Sarat Sethi"
description = "Is the bottom in for stocks? With CNBC's Scott Wapner and the 'Halftime Report' investment committee, Bryn Talkington, Sarat Sethi, Stephen Weiss and Joe Terranova."
author = CNBC Television
source = https://www.youtube.com/channel/UCrp_UI8XtuYfpiqluWLD7Lw
link = https://www.youtube.com/watch?v=NoJqrl6pZ8k
category = "News & Politics"
pubdate = Mon, 18 Jul 2022 00:00:00 -0000
enclosure = NoJqrl6pZ8k.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/NoJqrl6pZ8k/maxresdefault.jpg

