[item]
guid = oZCSOtWbEVo
title = "Don't listen to earnings reports if you don't have a long-term horizon, says Peter Andersen"
description = "Peter Andersen, Andersen Capital Management, joins 'Power Lunch' to discuss why it's time to have an 'intelligent fortitude' for investing this earnings season, stocks to find in today's environment and more."
author = CNBC Television
source = https://www.youtube.com/channel/UCrp_UI8XtuYfpiqluWLD7Lw
link = https://www.youtube.com/watch?v=oZCSOtWbEVo
category = "News & Politics"
pubdate = Mon, 18 Jul 2022 00:00:00 -0000
enclosure = oZCSOtWbEVo.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/oZCSOtWbEVo/maxresdefault.jpg

