[item]
guid = PoC4Tdf8LOc
title = "Twitter responds to Elon Musk's motion against expedited trial"
description = "CNBC's Julia Boorstin joins 'Fast Money' to report on Twitter's response to an Elon Musk motion against an expedited trial."
author = CNBC Television
source = https://www.youtube.com/channel/UCrp_UI8XtuYfpiqluWLD7Lw
link = https://www.youtube.com/watch?v=PoC4Tdf8LOc
category = "News & Politics"
pubdate = Mon, 18 Jul 2022 00:00:00 -0000
enclosure = PoC4Tdf8LOc.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/PoC4Tdf8LOc/maxresdefault.jpg

