[item]
guid = ppgCr0bzGeE
title = "Homebuilder sentiment drops 12 points"
description = "CNBC's Diana Olick joins 'The Exchange' to discuss homebuilder sentiment numbers, which are down 12 points in the last month."
author = CNBC Television
source = https://www.youtube.com/channel/UCrp_UI8XtuYfpiqluWLD7Lw
link = https://www.youtube.com/watch?v=ppgCr0bzGeE
category = "News & Politics"
pubdate = Mon, 18 Jul 2022 00:00:00 -0000
enclosure = ppgCr0bzGeE.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/ppgCr0bzGeE/maxresdefault.jpg

