[item]
guid = qdAdwXamPY0
title = "Executive Edge: Apple urges court to throw out app store injunction"
description = "The "Squawk Box" team discusses Apple's request to a court to throw out an injunction allowing developers to bypass Apple's app store payment system. And Alphabet completes a 20-for-1 split."
author = CNBC Television
source = https://www.youtube.com/channel/UCrp_UI8XtuYfpiqluWLD7Lw
link = https://www.youtube.com/watch?v=qdAdwXamPY0
category = "News & Politics"
pubdate = Mon, 18 Jul 2022 00:00:00 -0000
enclosure = qdAdwXamPY0.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/qdAdwXamPY0/maxresdefault.webp

