[item]
guid = qhAM_O6Cjt4
title = "SEB: We need to remember we have an energy crisis overall globally beyond oil"
description = "Bjarne Schieldrop, chief commodities analyst at SEB, says Russia is a major linchpin in the global energy markets, as it's the largest exporter of oil and natural gas in the world."
author = CNBC Television
source = https://www.youtube.com/channel/UCrp_UI8XtuYfpiqluWLD7Lw
link = https://www.youtube.com/watch?v=qhAM_O6Cjt4
category = "News & Politics"
pubdate = Mon, 18 Jul 2022 00:00:00 -0000
enclosure = qhAM_O6Cjt4.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/qhAM_O6Cjt4/hqdefault.jpg

