[item]
guid = T1qe1NoOhLM
title = "Presidential energy adviser Amos Hochstein breaks down Biden's Saudi trip"
description = "Amos Hochstein, Presidential energy adviser, joins 'Squawk Box' to discuss takeaways from Biden's Saudi Arabia trip and the energy sector."
author = CNBC Television
source = https://www.youtube.com/channel/UCrp_UI8XtuYfpiqluWLD7Lw
link = https://www.youtube.com/watch?v=T1qe1NoOhLM
category = "News & Politics"
pubdate = Mon, 18 Jul 2022 00:00:00 -0000
enclosure = T1qe1NoOhLM.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/T1qe1NoOhLM/hqdefault.jpg

