[item]
guid = tgJqPQwJsC0
title = "Higher hotel prices look sustainable if we deliver on the service, says Marriott CEO"
description = "Tony Capuano, Marriott CEO, joins 'Squawk on the Street' to discuss where Capuano sees the opportunity for Marriott going, when foreign travelers into the U.S. gets back to pre-pandemic levels and how the luxury business will perform amidst current market volatility."
author = CNBC Television
source = https://www.youtube.com/channel/UCrp_UI8XtuYfpiqluWLD7Lw
link = https://www.youtube.com/watch?v=tgJqPQwJsC0
category = "News & Politics"
pubdate = Mon, 18 Jul 2022 00:00:00 -0000
enclosure = tgJqPQwJsC0.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/tgJqPQwJsC0/hqdefault.jpg

