[item]
guid = Uq44Wl2rOeA
title = "It's difficult to ramp production because the scarcity of resources, says Airbus CEO"
description = "Guillaume Faury, Airbus CEO, joins 'TechCheck' to discuss aviation industry's ability to scale production, Faury's sense of the Chinese aviation market and information behind a current lawsuit the company is facing."
author = CNBC Television
source = https://www.youtube.com/channel/UCrp_UI8XtuYfpiqluWLD7Lw
link = https://www.youtube.com/watch?v=Uq44Wl2rOeA
category = "News & Politics"
pubdate = Mon, 18 Jul 2022 00:00:00 -0000
enclosure = Uq44Wl2rOeA.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/Uq44Wl2rOeA/hqdefault.jpg

