[item]
guid = UVzidaQK8z0
title = "Jim Cramer gives his take on Big Bank earnings"
description = "Jim Cramer, Mad Money host, joins 'Squawk Box' to discuss his first take on Mad Money's move to NYSE and big banks' earning reports."
author = CNBC Television
source = https://www.youtube.com/channel/UCrp_UI8XtuYfpiqluWLD7Lw
link = https://www.youtube.com/watch?v=UVzidaQK8z0
category = "News & Politics"
pubdate = Mon, 18 Jul 2022 00:00:00 -0000
enclosure = UVzidaQK8z0.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/UVzidaQK8z0/hqdefault.jpg

