[item]
guid = V4xvFBHUKYA
title = "The problem with streaming is it's so capital intensive, says MoffettNathanson's Michael Nathanson"
description = "Michael Nathanson, MoffettNathanson, joins 'Closing Bell' to discuss his thoughts on streaming, if we'll see less investment in streaming services and how Netflix will fare after its earnings following recent popular releases."
author = CNBC Television
source = https://www.youtube.com/channel/UCrp_UI8XtuYfpiqluWLD7Lw
link = https://www.youtube.com/watch?v=V4xvFBHUKYA
category = "News & Politics"
pubdate = Mon, 18 Jul 2022 00:00:00 -0000
enclosure = V4xvFBHUKYA.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/V4xvFBHUKYA/maxresdefault.webp

