[item]
guid = vWhWMmscnIg
title = "Jim Cramer: The consumer is strong; it will be difficult for the Fed to slow economy"
description = "‘Mad Money’ host Jim Cramer and the ‘Squawk on the Street’ team break down bank earnings."
author = CNBC Television
source = https://www.youtube.com/channel/UCrp_UI8XtuYfpiqluWLD7Lw
link = https://www.youtube.com/watch?v=vWhWMmscnIg
category = "News & Politics"
pubdate = Mon, 18 Jul 2022 00:00:00 -0000
enclosure = vWhWMmscnIg.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/vWhWMmscnIg/hqdefault.jpg

