[item]
guid = WeEJmr4nqHs
title = "Bank of America revenue beats forecasts, boosted by higher interest rates"
description = "CNBC's Leslie Picker joins 'Squawk Box' to report Bank of America earnings."
author = CNBC Television
source = https://www.youtube.com/channel/UCrp_UI8XtuYfpiqluWLD7Lw
link = https://www.youtube.com/watch?v=WeEJmr4nqHs
category = "News & Politics"
pubdate = Mon, 18 Jul 2022 00:00:00 -0000
enclosure = WeEJmr4nqHs.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/WeEJmr4nqHs/hqdefault.jpg

