[item]
guid = y4UEbNVbvlk
title = "Everyone knows we need to pass the Chips Act, says GlobalFoundries CEO"
description = "Thomas Caulfield, GlobalFoundries CEO, joins 'TechCheck' to discuss what's happening in Europe and the U.S. regarding chip production, Caulfield's thoughts on the details in the Chips Act and more."
author = CNBC Television
source = https://www.youtube.com/channel/UCrp_UI8XtuYfpiqluWLD7Lw
link = https://www.youtube.com/watch?v=y4UEbNVbvlk
category = "News & Politics"
pubdate = Mon, 18 Jul 2022 00:00:00 -0000
enclosure = y4UEbNVbvlk.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/y4UEbNVbvlk/maxresdefault.jpg

