[item]
guid = Y__yLsOpS3s
title = "Opening Bell, July 18, 2022"
description = "Watch the opening bell for the Nasdaq and the New York Stock Exchange from July 18, 2022."
author = CNBC Television
source = https://www.youtube.com/channel/UCrp_UI8XtuYfpiqluWLD7Lw
link = https://www.youtube.com/watch?v=Y__yLsOpS3s
category = "News & Politics"
pubdate = Mon, 18 Jul 2022 00:00:00 -0000
enclosure = Y__yLsOpS3s.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/Y__yLsOpS3s/hqdefault.jpg

