[item]
guid = YSXbhlYnthg
title = "Boeing CEO on supply chain disruptions: Engine constraints will last about 18 months"
description = "David Calhoun, Boeing CEO, joins 'Squawk Box' to discuss Delta ordering 100 Boeing planes and on 737 max production."
author = CNBC Television
source = https://www.youtube.com/channel/UCrp_UI8XtuYfpiqluWLD7Lw
link = https://www.youtube.com/watch?v=YSXbhlYnthg
category = "News & Politics"
pubdate = Mon, 18 Jul 2022 00:00:00 -0000
enclosure = YSXbhlYnthg.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/YSXbhlYnthg/hqdefault.jpg

