[item]
guid = Yx53Ft9KM0E
title = "Lockheed Martin CEO weighs in on CHIPS Act"
description = "CNBC's Ylan Mui talks to Lockheed Martin CEO Jim Taiclet about the importance of the CHIPS Act to U.S. national security."
author = CNBC Television
source = https://www.youtube.com/channel/UCrp_UI8XtuYfpiqluWLD7Lw
link = https://www.youtube.com/watch?v=Yx53Ft9KM0E
category = "News & Politics"
pubdate = Mon, 18 Jul 2022 00:00:00 -0000
enclosure = Yx53Ft9KM0E.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/Yx53Ft9KM0E/hqdefault.jpg

