[item]
guid = Z-BFENjObKw
title = "Earnings Exchange: IBM"
description = "Oppenheimer's Ari Wald joins 'The Exchange' to discuss stocks ahead of earnings, including IBM."
author = CNBC Television
source = https://www.youtube.com/channel/UCrp_UI8XtuYfpiqluWLD7Lw
link = https://www.youtube.com/watch?v=Z-BFENjObKw
category = "News & Politics"
pubdate = Mon, 18 Jul 2022 00:00:00 -0000
enclosure = Z-BFENjObKw.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/Z-BFENjObKw/maxresdefault.jpg

