[item]
guid = zNh9iYeBw8c
title = "Oil and natural gas prices will go higher due to lack of supply, says Truist's Dingmann"
description = "Neal Dingmann, Truist Securities, joins 'Squawk on the Street' to discuss his thoughts around oil and natural gas, how much higher said prices could go and what will drive companies to have less capital discipline."
author = CNBC Television
source = https://www.youtube.com/channel/UCrp_UI8XtuYfpiqluWLD7Lw
link = https://www.youtube.com/watch?v=zNh9iYeBw8c
category = "News & Politics"
pubdate = Mon, 18 Jul 2022 00:00:00 -0000
enclosure = zNh9iYeBw8c.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/zNh9iYeBw8c/maxresdefault.jpg

